FROM mcr.microsoft.com/vscode/devcontainers/javascript-node

RUN npm install -g create-react-app \
                   create-react-native-app \
                   react-native-cli

RUN npm install -g react-router@next \
                   react-router-dom@next

RUN npm i --save @fortawesome/fontawesome-svg-core \
                 @fortawesome/free-solid-svg-icons \
                 @fortawesome/react-fontawesome